// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module eucHW_sqrt_fixed_24_24_s (
        ap_clk,
        ap_rst,
        x,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [22:0] x;
output  [11:0] ap_return;

wire   [26:0] x_l_I_V_24_fu_292_p3;
reg   [26:0] x_l_I_V_24_reg_1109;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_11001;
wire   [11:0] res_I_V_25_fu_300_p3;
reg   [11:0] res_I_V_25_reg_1115;
wire   [0:0] icmp_ln489_1_fu_340_p2;
reg   [0:0] icmp_ln489_1_reg_1121;
wire   [4:0] sub_ln265_1_fu_346_p2;
reg   [4:0] sub_ln265_1_reg_1127;
wire   [26:0] x_l_I_V_26_fu_449_p3;
reg   [26:0] x_l_I_V_26_reg_1132;
wire   [11:0] res_I_V_27_fu_457_p3;
reg   [11:0] res_I_V_27_reg_1138;
wire   [0:0] icmp_ln489_3_fu_497_p2;
reg   [0:0] icmp_ln489_3_reg_1144;
wire   [6:0] sub_ln265_3_fu_503_p2;
reg   [6:0] sub_ln265_3_reg_1150;
wire   [26:0] x_l_I_V_28_fu_606_p3;
reg   [26:0] x_l_I_V_28_reg_1155;
wire   [11:0] res_I_V_29_fu_614_p3;
reg   [11:0] res_I_V_29_reg_1161;
wire   [0:0] icmp_ln489_5_fu_654_p2;
reg   [0:0] icmp_ln489_5_reg_1167;
wire   [8:0] sub_ln265_5_fu_660_p2;
reg   [8:0] sub_ln265_5_reg_1173;
wire   [26:0] x_l_I_V_29_fu_763_p3;
reg   [26:0] x_l_I_V_29_reg_1178;
wire   [11:0] res_I_V_fu_771_p3;
reg   [11:0] res_I_V_reg_1184;
wire   [0:0] icmp_ln489_7_fu_811_p2;
reg   [0:0] icmp_ln489_7_reg_1190;
wire   [10:0] sub_ln265_7_fu_817_p2;
reg   [10:0] sub_ln265_7_reg_1196;
wire   [26:0] x_l_I_V_31_fu_920_p3;
reg   [26:0] x_l_I_V_31_reg_1201;
wire   [0:0] icmp_ln489_9_fu_968_p2;
reg   [0:0] icmp_ln489_9_reg_1207;
wire   [12:0] sub_ln265_9_fu_974_p2;
reg   [12:0] sub_ln265_9_reg_1212;
wire   [11:0] res_I_V_33_fu_990_p3;
reg   [11:0] res_I_V_33_reg_1217;
wire    ap_block_pp0_stage0;
wire   [0:0] tmp_fu_176_p3;
wire   [0:0] xor_ln265_fu_184_p2;
wire   [26:0] zext_ln712_fu_172_p1;
wire   [2:0] select_ln323_fu_190_p3;
wire   [26:0] p_Result_36_fu_198_p5;
wire   [11:0] res_I_V_24_fu_218_p3;
wire   [1:0] p_Result_s_fu_226_p4;
wire   [26:0] x_l_I_V_23_fu_210_p3;
wire   [2:0] tmp_1_fu_236_p3;
wire   [3:0] p_Result_1_fu_244_p4;
wire   [3:0] zext_ln489_fu_254_p1;
wire   [3:0] sub_ln265_fu_264_p2;
wire   [0:0] icmp_ln489_fu_258_p2;
wire   [26:0] p_Result_37_fu_270_p5;
wire   [11:0] p_Result_38_fu_282_p4;
wire   [2:0] p_Result_4_fu_308_p4;
wire   [3:0] tmp_2_fu_318_p3;
wire   [4:0] p_Result_5_fu_326_p4;
wire   [4:0] zext_ln489_1_fu_336_p1;
wire   [26:0] p_Result_39_fu_352_p5;
wire   [11:0] p_Result_40_fu_362_p4;
wire   [11:0] res_I_V_26_fu_377_p3;
wire   [3:0] p_Result_8_fu_383_p4;
wire   [26:0] x_l_I_V_25_fu_371_p3;
wire   [4:0] tmp_3_fu_393_p3;
wire   [5:0] p_Result_9_fu_401_p4;
wire   [5:0] zext_ln489_2_fu_411_p1;
wire   [5:0] sub_ln265_2_fu_421_p2;
wire   [0:0] icmp_ln489_2_fu_415_p2;
wire   [26:0] p_Result_41_fu_427_p5;
wire   [11:0] p_Result_42_fu_439_p4;
wire   [4:0] p_Result_10_fu_465_p4;
wire   [5:0] tmp_4_fu_475_p3;
wire   [6:0] p_Result_11_fu_483_p4;
wire   [6:0] zext_ln489_3_fu_493_p1;
wire   [26:0] p_Result_43_fu_509_p5;
wire   [11:0] p_Result_44_fu_519_p4;
wire   [11:0] res_I_V_28_fu_534_p3;
wire   [5:0] p_Result_13_fu_540_p4;
wire   [26:0] x_l_I_V_27_fu_528_p3;
wire   [6:0] tmp_5_fu_550_p3;
wire   [7:0] p_Result_14_fu_558_p4;
wire   [7:0] zext_ln489_4_fu_568_p1;
wire   [7:0] sub_ln265_4_fu_578_p2;
wire   [0:0] icmp_ln489_4_fu_572_p2;
wire   [26:0] p_Result_45_fu_584_p5;
wire   [11:0] p_Result_46_fu_596_p4;
wire   [6:0] p_Result_16_fu_622_p4;
wire   [7:0] tmp_6_fu_632_p3;
wire   [8:0] p_Result_17_fu_640_p4;
wire   [8:0] zext_ln489_5_fu_650_p1;
wire   [26:0] p_Result_47_fu_666_p5;
wire   [11:0] p_Result_48_fu_676_p4;
wire   [11:0] res_I_V_30_fu_691_p3;
wire   [7:0] p_Result_19_fu_697_p4;
wire   [26:0] x_l_I_V_fu_685_p3;
wire   [8:0] tmp_7_fu_707_p3;
wire   [9:0] p_Result_20_fu_715_p4;
wire   [9:0] zext_ln489_6_fu_725_p1;
wire   [9:0] sub_ln265_6_fu_735_p2;
wire   [0:0] icmp_ln489_6_fu_729_p2;
wire   [26:0] p_Result_49_fu_741_p5;
wire   [11:0] p_Result_50_fu_753_p4;
wire   [8:0] p_Result_22_fu_779_p4;
wire   [9:0] tmp_8_fu_789_p3;
wire   [10:0] p_Result_23_fu_797_p4;
wire   [10:0] zext_ln489_7_fu_807_p1;
wire   [26:0] p_Result_51_fu_823_p5;
wire   [11:0] p_Result_52_fu_833_p4;
wire   [11:0] res_I_V_31_fu_848_p3;
wire   [9:0] p_Result_25_fu_854_p4;
wire   [26:0] x_l_I_V_30_fu_842_p3;
wire   [10:0] tmp_9_fu_864_p3;
wire   [11:0] p_Result_26_fu_872_p4;
wire   [11:0] zext_ln489_8_fu_882_p1;
wire   [11:0] sub_ln265_8_fu_892_p2;
wire   [0:0] icmp_ln489_8_fu_886_p2;
wire   [26:0] p_Result_53_fu_898_p5;
wire   [11:0] p_Result_54_fu_910_p4;
wire   [11:0] res_I_V_32_fu_928_p3;
wire   [10:0] p_Result_28_fu_936_p4;
wire   [11:0] tmp_s_fu_946_p3;
wire   [12:0] p_Result_29_fu_954_p4;
wire   [12:0] zext_ln489_9_fu_964_p1;
wire   [11:0] p_Result_56_fu_980_p4;
wire   [26:0] p_Result_55_fu_998_p5;
wire   [26:0] x_l_I_V_32_fu_1008_p3;
wire   [12:0] tmp_10_fu_1014_p3;
wire   [13:0] trunc_ln640_fu_1021_p1;
wire   [13:0] zext_ln489_10_fu_1025_p1;
wire   [13:0] sub_ln265_10_fu_1035_p2;
wire   [0:0] icmp_ln489_10_fu_1029_p2;
wire   [26:0] p_Result_57_fu_1041_p5;
wire   [11:0] p_Result_58_fu_1053_p4;
wire   [11:0] res_I_V_34_fu_1070_p3;
wire   [24:0] mul_I_V_fu_1077_p3;
wire   [26:0] x_l_I_V_33_fu_1062_p3;
wire   [26:0] zext_ln717_fu_1085_p1;
wire   [0:0] p_Result_s_116_fu_1089_p2;
wire   [11:0] res_I_V_22_fu_1095_p2;
reg   [22:0] x_int_reg;
wire    ap_ce_reg;

always @ (posedge ap_clk) begin
    x_int_reg <= x;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln489_1_reg_1121 <= icmp_ln489_1_fu_340_p2;
        icmp_ln489_3_reg_1144 <= icmp_ln489_3_fu_497_p2;
        icmp_ln489_5_reg_1167 <= icmp_ln489_5_fu_654_p2;
        icmp_ln489_7_reg_1190 <= icmp_ln489_7_fu_811_p2;
        icmp_ln489_9_reg_1207 <= icmp_ln489_9_fu_968_p2;
        res_I_V_25_reg_1115 <= res_I_V_25_fu_300_p3;
        res_I_V_27_reg_1138 <= res_I_V_27_fu_457_p3;
        res_I_V_29_reg_1161 <= res_I_V_29_fu_614_p3;
        res_I_V_33_reg_1217 <= res_I_V_33_fu_990_p3;
        res_I_V_reg_1184 <= res_I_V_fu_771_p3;
        sub_ln265_1_reg_1127 <= sub_ln265_1_fu_346_p2;
        sub_ln265_3_reg_1150 <= sub_ln265_3_fu_503_p2;
        sub_ln265_5_reg_1173 <= sub_ln265_5_fu_660_p2;
        sub_ln265_7_reg_1196 <= sub_ln265_7_fu_817_p2;
        sub_ln265_9_reg_1212 <= sub_ln265_9_fu_974_p2;
        x_l_I_V_24_reg_1109 <= x_l_I_V_24_fu_292_p3;
        x_l_I_V_26_reg_1132 <= x_l_I_V_26_fu_449_p3;
        x_l_I_V_28_reg_1155 <= x_l_I_V_28_fu_606_p3;
        x_l_I_V_29_reg_1178 <= x_l_I_V_29_fu_763_p3;
        x_l_I_V_31_reg_1201 <= x_l_I_V_31_fu_920_p3;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_return = ((p_Result_s_116_fu_1089_p2[0:0] == 1'b1) ? res_I_V_22_fu_1095_p2 : res_I_V_34_fu_1070_p3);

assign icmp_ln489_10_fu_1029_p2 = ((trunc_ln640_fu_1021_p1 < zext_ln489_10_fu_1025_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_1_fu_340_p2 = ((p_Result_5_fu_326_p4 < zext_ln489_1_fu_336_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_2_fu_415_p2 = ((p_Result_9_fu_401_p4 < zext_ln489_2_fu_411_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_3_fu_497_p2 = ((p_Result_11_fu_483_p4 < zext_ln489_3_fu_493_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_4_fu_572_p2 = ((p_Result_14_fu_558_p4 < zext_ln489_4_fu_568_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_5_fu_654_p2 = ((p_Result_17_fu_640_p4 < zext_ln489_5_fu_650_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_6_fu_729_p2 = ((p_Result_20_fu_715_p4 < zext_ln489_6_fu_725_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_7_fu_811_p2 = ((p_Result_23_fu_797_p4 < zext_ln489_7_fu_807_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_8_fu_886_p2 = ((p_Result_26_fu_872_p4 < zext_ln489_8_fu_882_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_9_fu_968_p2 = ((p_Result_29_fu_954_p4 < zext_ln489_9_fu_964_p1) ? 1'b1 : 1'b0);

assign icmp_ln489_fu_258_p2 = ((p_Result_1_fu_244_p4 < zext_ln489_fu_254_p1) ? 1'b1 : 1'b0);

assign mul_I_V_fu_1077_p3 = {{13'd0}, {res_I_V_34_fu_1070_p3}};

assign p_Result_10_fu_465_p4 = {{res_I_V_27_fu_457_p3[11:7]}};

assign p_Result_11_fu_483_p4 = {{x_l_I_V_26_fu_449_p3[20:14]}};

assign p_Result_13_fu_540_p4 = {{res_I_V_28_fu_534_p3[11:6]}};

assign p_Result_14_fu_558_p4 = {{x_l_I_V_27_fu_528_p3[19:12]}};

assign p_Result_16_fu_622_p4 = {{res_I_V_29_fu_614_p3[11:5]}};

assign p_Result_17_fu_640_p4 = {{x_l_I_V_28_fu_606_p3[18:10]}};

assign p_Result_19_fu_697_p4 = {{res_I_V_30_fu_691_p3[11:4]}};

assign p_Result_1_fu_244_p4 = {{x_l_I_V_23_fu_210_p3[23:20]}};

assign p_Result_20_fu_715_p4 = {{x_l_I_V_fu_685_p3[17:8]}};

assign p_Result_22_fu_779_p4 = {{res_I_V_fu_771_p3[11:3]}};

assign p_Result_23_fu_797_p4 = {{x_l_I_V_29_fu_763_p3[16:6]}};

assign p_Result_25_fu_854_p4 = {{res_I_V_31_fu_848_p3[11:2]}};

assign p_Result_26_fu_872_p4 = {{x_l_I_V_30_fu_842_p3[15:4]}};

assign p_Result_28_fu_936_p4 = {{res_I_V_32_fu_928_p3[11:1]}};

assign p_Result_29_fu_954_p4 = {{x_l_I_V_31_fu_920_p3[14:2]}};

assign p_Result_36_fu_198_p5 = {{zext_ln712_fu_172_p1[26:25]}, {select_ln323_fu_190_p3}, {zext_ln712_fu_172_p1[21:0]}};

assign p_Result_37_fu_270_p5 = {{x_l_I_V_23_fu_210_p3[26:24]}, {sub_ln265_fu_264_p2}, {x_l_I_V_23_fu_210_p3[19:0]}};

assign p_Result_38_fu_282_p4 = {res_I_V_24_fu_218_p3[12 - 1:11], |(1'd1), res_I_V_24_fu_218_p3[9:0]};

assign p_Result_39_fu_352_p5 = {{x_l_I_V_24_reg_1109[26:23]}, {sub_ln265_1_reg_1127}, {x_l_I_V_24_reg_1109[17:0]}};

assign p_Result_40_fu_362_p4 = {res_I_V_25_reg_1115[12 - 1:10], |(1'd1), res_I_V_25_reg_1115[8:0]};

assign p_Result_41_fu_427_p5 = {{x_l_I_V_25_fu_371_p3[26:22]}, {sub_ln265_2_fu_421_p2}, {x_l_I_V_25_fu_371_p3[15:0]}};

assign p_Result_42_fu_439_p4 = {res_I_V_26_fu_377_p3[12 - 1:9], |(1'd1), res_I_V_26_fu_377_p3[7:0]};

assign p_Result_43_fu_509_p5 = {{x_l_I_V_26_reg_1132[26:21]}, {sub_ln265_3_reg_1150}, {x_l_I_V_26_reg_1132[13:0]}};

assign p_Result_44_fu_519_p4 = {res_I_V_27_reg_1138[12 - 1:8], |(1'd1), res_I_V_27_reg_1138[6:0]};

assign p_Result_45_fu_584_p5 = {{x_l_I_V_27_fu_528_p3[26:20]}, {sub_ln265_4_fu_578_p2}, {x_l_I_V_27_fu_528_p3[11:0]}};

assign p_Result_46_fu_596_p4 = {res_I_V_28_fu_534_p3[12 - 1:7], |(1'd1), res_I_V_28_fu_534_p3[5:0]};

assign p_Result_47_fu_666_p5 = {{x_l_I_V_28_reg_1155[26:19]}, {sub_ln265_5_reg_1173}, {x_l_I_V_28_reg_1155[9:0]}};

assign p_Result_48_fu_676_p4 = {res_I_V_29_reg_1161[12 - 1:6], |(1'd1), res_I_V_29_reg_1161[4:0]};

assign p_Result_49_fu_741_p5 = {{x_l_I_V_fu_685_p3[26:18]}, {sub_ln265_6_fu_735_p2}, {x_l_I_V_fu_685_p3[7:0]}};

assign p_Result_4_fu_308_p4 = {{res_I_V_25_fu_300_p3[11:9]}};

assign p_Result_50_fu_753_p4 = {res_I_V_30_fu_691_p3[12 - 1:5], |(1'd1), res_I_V_30_fu_691_p3[3:0]};

assign p_Result_51_fu_823_p5 = {{x_l_I_V_29_reg_1178[26:17]}, {sub_ln265_7_reg_1196}, {x_l_I_V_29_reg_1178[5:0]}};

assign p_Result_52_fu_833_p4 = {res_I_V_reg_1184[12 - 1:4], |(1'd1), res_I_V_reg_1184[2:0]};

assign p_Result_53_fu_898_p5 = {{x_l_I_V_30_fu_842_p3[26:16]}, {sub_ln265_8_fu_892_p2}, {x_l_I_V_30_fu_842_p3[3:0]}};

assign p_Result_54_fu_910_p4 = {res_I_V_31_fu_848_p3[12 - 1:3], |(1'd1), res_I_V_31_fu_848_p3[1:0]};

assign p_Result_55_fu_998_p5 = {{x_l_I_V_31_reg_1201[26:15]}, {sub_ln265_9_reg_1212}, {x_l_I_V_31_reg_1201[1:0]}};

assign p_Result_56_fu_980_p4 = {res_I_V_32_fu_928_p3[12 - 1:2], |(1'd1), res_I_V_32_fu_928_p3[0:0]};

assign p_Result_57_fu_1041_p5 = {{x_l_I_V_32_fu_1008_p3[26:14]}, {sub_ln265_10_fu_1035_p2}};

assign p_Result_58_fu_1053_p4 = {res_I_V_33_reg_1217[12-1:1], |(1'd1)};

assign p_Result_5_fu_326_p4 = {{x_l_I_V_24_fu_292_p3[22:18]}};

assign p_Result_8_fu_383_p4 = {{res_I_V_26_fu_377_p3[11:8]}};

assign p_Result_9_fu_401_p4 = {{x_l_I_V_25_fu_371_p3[21:16]}};

assign p_Result_s_116_fu_1089_p2 = ((x_l_I_V_33_fu_1062_p3 > zext_ln717_fu_1085_p1) ? 1'b1 : 1'b0);

assign p_Result_s_fu_226_p4 = {{res_I_V_24_fu_218_p3[11:10]}};

assign res_I_V_22_fu_1095_p2 = (res_I_V_34_fu_1070_p3 + 12'd1);

assign res_I_V_24_fu_218_p3 = ((tmp_fu_176_p3[0:0] == 1'b1) ? 12'd2048 : 12'd0);

assign res_I_V_25_fu_300_p3 = ((icmp_ln489_fu_258_p2[0:0] == 1'b1) ? res_I_V_24_fu_218_p3 : p_Result_38_fu_282_p4);

assign res_I_V_26_fu_377_p3 = ((icmp_ln489_1_reg_1121[0:0] == 1'b1) ? res_I_V_25_reg_1115 : p_Result_40_fu_362_p4);

assign res_I_V_27_fu_457_p3 = ((icmp_ln489_2_fu_415_p2[0:0] == 1'b1) ? res_I_V_26_fu_377_p3 : p_Result_42_fu_439_p4);

assign res_I_V_28_fu_534_p3 = ((icmp_ln489_3_reg_1144[0:0] == 1'b1) ? res_I_V_27_reg_1138 : p_Result_44_fu_519_p4);

assign res_I_V_29_fu_614_p3 = ((icmp_ln489_4_fu_572_p2[0:0] == 1'b1) ? res_I_V_28_fu_534_p3 : p_Result_46_fu_596_p4);

assign res_I_V_30_fu_691_p3 = ((icmp_ln489_5_reg_1167[0:0] == 1'b1) ? res_I_V_29_reg_1161 : p_Result_48_fu_676_p4);

assign res_I_V_31_fu_848_p3 = ((icmp_ln489_7_reg_1190[0:0] == 1'b1) ? res_I_V_reg_1184 : p_Result_52_fu_833_p4);

assign res_I_V_32_fu_928_p3 = ((icmp_ln489_8_fu_886_p2[0:0] == 1'b1) ? res_I_V_31_fu_848_p3 : p_Result_54_fu_910_p4);

assign res_I_V_33_fu_990_p3 = ((icmp_ln489_9_fu_968_p2[0:0] == 1'b1) ? res_I_V_32_fu_928_p3 : p_Result_56_fu_980_p4);

assign res_I_V_34_fu_1070_p3 = ((icmp_ln489_10_fu_1029_p2[0:0] == 1'b1) ? res_I_V_33_reg_1217 : p_Result_58_fu_1053_p4);

assign res_I_V_fu_771_p3 = ((icmp_ln489_6_fu_729_p2[0:0] == 1'b1) ? res_I_V_30_fu_691_p3 : p_Result_50_fu_753_p4);

assign select_ln323_fu_190_p3 = ((xor_ln265_fu_184_p2[0:0] == 1'b1) ? 3'd7 : 3'd0);

assign sub_ln265_10_fu_1035_p2 = (trunc_ln640_fu_1021_p1 - zext_ln489_10_fu_1025_p1);

assign sub_ln265_1_fu_346_p2 = (p_Result_5_fu_326_p4 - zext_ln489_1_fu_336_p1);

assign sub_ln265_2_fu_421_p2 = (p_Result_9_fu_401_p4 - zext_ln489_2_fu_411_p1);

assign sub_ln265_3_fu_503_p2 = (p_Result_11_fu_483_p4 - zext_ln489_3_fu_493_p1);

assign sub_ln265_4_fu_578_p2 = (p_Result_14_fu_558_p4 - zext_ln489_4_fu_568_p1);

assign sub_ln265_5_fu_660_p2 = (p_Result_17_fu_640_p4 - zext_ln489_5_fu_650_p1);

assign sub_ln265_6_fu_735_p2 = (p_Result_20_fu_715_p4 - zext_ln489_6_fu_725_p1);

assign sub_ln265_7_fu_817_p2 = (p_Result_23_fu_797_p4 - zext_ln489_7_fu_807_p1);

assign sub_ln265_8_fu_892_p2 = (p_Result_26_fu_872_p4 - zext_ln489_8_fu_882_p1);

assign sub_ln265_9_fu_974_p2 = (p_Result_29_fu_954_p4 - zext_ln489_9_fu_964_p1);

assign sub_ln265_fu_264_p2 = (p_Result_1_fu_244_p4 - zext_ln489_fu_254_p1);

assign tmp_10_fu_1014_p3 = {{res_I_V_33_reg_1217}, {1'd1}};

assign tmp_1_fu_236_p3 = {{p_Result_s_fu_226_p4}, {1'd1}};

assign tmp_2_fu_318_p3 = {{p_Result_4_fu_308_p4}, {1'd1}};

assign tmp_3_fu_393_p3 = {{p_Result_8_fu_383_p4}, {1'd1}};

assign tmp_4_fu_475_p3 = {{p_Result_10_fu_465_p4}, {1'd1}};

assign tmp_5_fu_550_p3 = {{p_Result_13_fu_540_p4}, {1'd1}};

assign tmp_6_fu_632_p3 = {{p_Result_16_fu_622_p4}, {1'd1}};

assign tmp_7_fu_707_p3 = {{p_Result_19_fu_697_p4}, {1'd1}};

assign tmp_8_fu_789_p3 = {{p_Result_22_fu_779_p4}, {1'd1}};

assign tmp_9_fu_864_p3 = {{p_Result_25_fu_854_p4}, {1'd1}};

assign tmp_fu_176_p3 = x_int_reg[32'd22];

assign tmp_s_fu_946_p3 = {{p_Result_28_fu_936_p4}, {1'd1}};

assign trunc_ln640_fu_1021_p1 = x_l_I_V_32_fu_1008_p3[13:0];

assign x_l_I_V_23_fu_210_p3 = ((tmp_fu_176_p3[0:0] == 1'b1) ? p_Result_36_fu_198_p5 : zext_ln712_fu_172_p1);

assign x_l_I_V_24_fu_292_p3 = ((icmp_ln489_fu_258_p2[0:0] == 1'b1) ? x_l_I_V_23_fu_210_p3 : p_Result_37_fu_270_p5);

assign x_l_I_V_25_fu_371_p3 = ((icmp_ln489_1_reg_1121[0:0] == 1'b1) ? x_l_I_V_24_reg_1109 : p_Result_39_fu_352_p5);

assign x_l_I_V_26_fu_449_p3 = ((icmp_ln489_2_fu_415_p2[0:0] == 1'b1) ? x_l_I_V_25_fu_371_p3 : p_Result_41_fu_427_p5);

assign x_l_I_V_27_fu_528_p3 = ((icmp_ln489_3_reg_1144[0:0] == 1'b1) ? x_l_I_V_26_reg_1132 : p_Result_43_fu_509_p5);

assign x_l_I_V_28_fu_606_p3 = ((icmp_ln489_4_fu_572_p2[0:0] == 1'b1) ? x_l_I_V_27_fu_528_p3 : p_Result_45_fu_584_p5);

assign x_l_I_V_29_fu_763_p3 = ((icmp_ln489_6_fu_729_p2[0:0] == 1'b1) ? x_l_I_V_fu_685_p3 : p_Result_49_fu_741_p5);

assign x_l_I_V_30_fu_842_p3 = ((icmp_ln489_7_reg_1190[0:0] == 1'b1) ? x_l_I_V_29_reg_1178 : p_Result_51_fu_823_p5);

assign x_l_I_V_31_fu_920_p3 = ((icmp_ln489_8_fu_886_p2[0:0] == 1'b1) ? x_l_I_V_30_fu_842_p3 : p_Result_53_fu_898_p5);

assign x_l_I_V_32_fu_1008_p3 = ((icmp_ln489_9_reg_1207[0:0] == 1'b1) ? x_l_I_V_31_reg_1201 : p_Result_55_fu_998_p5);

assign x_l_I_V_33_fu_1062_p3 = ((icmp_ln489_10_fu_1029_p2[0:0] == 1'b1) ? x_l_I_V_32_fu_1008_p3 : p_Result_57_fu_1041_p5);

assign x_l_I_V_fu_685_p3 = ((icmp_ln489_5_reg_1167[0:0] == 1'b1) ? x_l_I_V_28_reg_1155 : p_Result_47_fu_666_p5);

assign xor_ln265_fu_184_p2 = (tmp_fu_176_p3 ^ 1'd1);

assign zext_ln489_10_fu_1025_p1 = tmp_10_fu_1014_p3;

assign zext_ln489_1_fu_336_p1 = tmp_2_fu_318_p3;

assign zext_ln489_2_fu_411_p1 = tmp_3_fu_393_p3;

assign zext_ln489_3_fu_493_p1 = tmp_4_fu_475_p3;

assign zext_ln489_4_fu_568_p1 = tmp_5_fu_550_p3;

assign zext_ln489_5_fu_650_p1 = tmp_6_fu_632_p3;

assign zext_ln489_6_fu_725_p1 = tmp_7_fu_707_p3;

assign zext_ln489_7_fu_807_p1 = tmp_8_fu_789_p3;

assign zext_ln489_8_fu_882_p1 = tmp_9_fu_864_p3;

assign zext_ln489_9_fu_964_p1 = tmp_s_fu_946_p3;

assign zext_ln489_fu_254_p1 = tmp_1_fu_236_p3;

assign zext_ln712_fu_172_p1 = x_int_reg;

assign zext_ln717_fu_1085_p1 = mul_I_V_fu_1077_p3;

endmodule //eucHW_sqrt_fixed_24_24_s
