-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity eucHW_sqrt_fixed_24_24_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (22 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (11 downto 0) );
end;


architecture behav of eucHW_sqrt_fixed_24_24_s is 
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv12_800 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal x_l_I_V_24_fu_292_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal x_l_I_V_24_reg_1109 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal res_I_V_25_fu_300_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal res_I_V_25_reg_1115 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln489_1_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln489_1_reg_1121 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln265_1_fu_346_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln265_1_reg_1127 : STD_LOGIC_VECTOR (4 downto 0);
    signal x_l_I_V_26_fu_449_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal x_l_I_V_26_reg_1132 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_I_V_27_fu_457_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal res_I_V_27_reg_1138 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln489_3_fu_497_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln489_3_reg_1144 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln265_3_fu_503_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln265_3_reg_1150 : STD_LOGIC_VECTOR (6 downto 0);
    signal x_l_I_V_28_fu_606_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal x_l_I_V_28_reg_1155 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_I_V_29_fu_614_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal res_I_V_29_reg_1161 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln489_5_fu_654_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln489_5_reg_1167 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln265_5_fu_660_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln265_5_reg_1173 : STD_LOGIC_VECTOR (8 downto 0);
    signal x_l_I_V_29_fu_763_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal x_l_I_V_29_reg_1178 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_I_V_fu_771_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal res_I_V_reg_1184 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln489_7_fu_811_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln489_7_reg_1190 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln265_7_fu_817_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln265_7_reg_1196 : STD_LOGIC_VECTOR (10 downto 0);
    signal x_l_I_V_31_fu_920_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal x_l_I_V_31_reg_1201 : STD_LOGIC_VECTOR (26 downto 0);
    signal icmp_ln489_9_fu_968_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln489_9_reg_1207 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln265_9_fu_974_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln265_9_reg_1212 : STD_LOGIC_VECTOR (12 downto 0);
    signal res_I_V_33_fu_990_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal res_I_V_33_reg_1217 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_fu_176_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln265_fu_184_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln712_fu_172_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal select_ln323_fu_190_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Result_36_fu_198_p5 : STD_LOGIC_VECTOR (26 downto 0);
    signal res_I_V_24_fu_218_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_s_fu_226_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal x_l_I_V_23_fu_210_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_1_fu_236_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Result_1_fu_244_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln489_fu_254_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln265_fu_264_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln489_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_37_fu_270_p5 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Result_38_fu_282_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_4_fu_308_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_318_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_5_fu_326_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln489_1_fu_336_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_Result_39_fu_352_p5 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Result_40_fu_362_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal res_I_V_26_fu_377_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_8_fu_383_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal x_l_I_V_25_fu_371_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_3_fu_393_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_Result_9_fu_401_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln489_2_fu_411_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln265_2_fu_421_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln489_2_fu_415_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_41_fu_427_p5 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Result_42_fu_439_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_10_fu_465_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_4_fu_475_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Result_11_fu_483_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln489_3_fu_493_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_43_fu_509_p5 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Result_44_fu_519_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal res_I_V_28_fu_534_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_13_fu_540_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal x_l_I_V_27_fu_528_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_5_fu_550_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_14_fu_558_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln489_4_fu_568_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln265_4_fu_578_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln489_4_fu_572_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_45_fu_584_p5 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Result_46_fu_596_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_16_fu_622_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_6_fu_632_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_17_fu_640_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln489_5_fu_650_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Result_47_fu_666_p5 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Result_48_fu_676_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal res_I_V_30_fu_691_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_19_fu_697_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal x_l_I_V_fu_685_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_7_fu_707_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Result_20_fu_715_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln489_6_fu_725_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln265_6_fu_735_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln489_6_fu_729_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_49_fu_741_p5 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Result_50_fu_753_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_22_fu_779_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_8_fu_789_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_Result_23_fu_797_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln489_7_fu_807_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Result_51_fu_823_p5 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Result_52_fu_833_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal res_I_V_31_fu_848_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_25_fu_854_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal x_l_I_V_30_fu_842_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_9_fu_864_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Result_26_fu_872_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln489_8_fu_882_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln265_8_fu_892_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln489_8_fu_886_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_53_fu_898_p5 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Result_54_fu_910_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal res_I_V_32_fu_928_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_28_fu_936_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_s_fu_946_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_29_fu_954_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln489_9_fu_964_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_Result_56_fu_980_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_55_fu_998_p5 : STD_LOGIC_VECTOR (26 downto 0);
    signal x_l_I_V_32_fu_1008_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_10_fu_1014_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln640_fu_1021_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln489_10_fu_1025_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sub_ln265_10_fu_1035_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln489_10_fu_1029_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_57_fu_1041_p5 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Result_58_fu_1053_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal res_I_V_34_fu_1070_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_I_V_fu_1077_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal x_l_I_V_33_fu_1062_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal zext_ln717_fu_1085_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Result_s_116_fu_1089_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_I_V_22_fu_1095_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal x_int_reg : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin




    x_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            x_int_reg <= x;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln489_1_reg_1121 <= icmp_ln489_1_fu_340_p2;
                icmp_ln489_3_reg_1144 <= icmp_ln489_3_fu_497_p2;
                icmp_ln489_5_reg_1167 <= icmp_ln489_5_fu_654_p2;
                icmp_ln489_7_reg_1190 <= icmp_ln489_7_fu_811_p2;
                icmp_ln489_9_reg_1207 <= icmp_ln489_9_fu_968_p2;
                res_I_V_25_reg_1115 <= res_I_V_25_fu_300_p3;
                res_I_V_27_reg_1138 <= res_I_V_27_fu_457_p3;
                res_I_V_29_reg_1161 <= res_I_V_29_fu_614_p3;
                res_I_V_33_reg_1217 <= res_I_V_33_fu_990_p3;
                res_I_V_reg_1184 <= res_I_V_fu_771_p3;
                sub_ln265_1_reg_1127 <= sub_ln265_1_fu_346_p2;
                sub_ln265_3_reg_1150 <= sub_ln265_3_fu_503_p2;
                sub_ln265_5_reg_1173 <= sub_ln265_5_fu_660_p2;
                sub_ln265_7_reg_1196 <= sub_ln265_7_fu_817_p2;
                sub_ln265_9_reg_1212 <= sub_ln265_9_fu_974_p2;
                x_l_I_V_24_reg_1109 <= x_l_I_V_24_fu_292_p3;
                x_l_I_V_26_reg_1132 <= x_l_I_V_26_fu_449_p3;
                x_l_I_V_28_reg_1155 <= x_l_I_V_28_fu_606_p3;
                x_l_I_V_29_reg_1178 <= x_l_I_V_29_fu_763_p3;
                x_l_I_V_31_reg_1201 <= x_l_I_V_31_fu_920_p3;
            end if;
        end if;
    end process;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return <= 
        res_I_V_22_fu_1095_p2 when (p_Result_s_116_fu_1089_p2(0) = '1') else 
        res_I_V_34_fu_1070_p3;
    icmp_ln489_10_fu_1029_p2 <= "1" when (unsigned(trunc_ln640_fu_1021_p1) < unsigned(zext_ln489_10_fu_1025_p1)) else "0";
    icmp_ln489_1_fu_340_p2 <= "1" when (unsigned(p_Result_5_fu_326_p4) < unsigned(zext_ln489_1_fu_336_p1)) else "0";
    icmp_ln489_2_fu_415_p2 <= "1" when (unsigned(p_Result_9_fu_401_p4) < unsigned(zext_ln489_2_fu_411_p1)) else "0";
    icmp_ln489_3_fu_497_p2 <= "1" when (unsigned(p_Result_11_fu_483_p4) < unsigned(zext_ln489_3_fu_493_p1)) else "0";
    icmp_ln489_4_fu_572_p2 <= "1" when (unsigned(p_Result_14_fu_558_p4) < unsigned(zext_ln489_4_fu_568_p1)) else "0";
    icmp_ln489_5_fu_654_p2 <= "1" when (unsigned(p_Result_17_fu_640_p4) < unsigned(zext_ln489_5_fu_650_p1)) else "0";
    icmp_ln489_6_fu_729_p2 <= "1" when (unsigned(p_Result_20_fu_715_p4) < unsigned(zext_ln489_6_fu_725_p1)) else "0";
    icmp_ln489_7_fu_811_p2 <= "1" when (unsigned(p_Result_23_fu_797_p4) < unsigned(zext_ln489_7_fu_807_p1)) else "0";
    icmp_ln489_8_fu_886_p2 <= "1" when (unsigned(p_Result_26_fu_872_p4) < unsigned(zext_ln489_8_fu_882_p1)) else "0";
    icmp_ln489_9_fu_968_p2 <= "1" when (unsigned(p_Result_29_fu_954_p4) < unsigned(zext_ln489_9_fu_964_p1)) else "0";
    icmp_ln489_fu_258_p2 <= "1" when (unsigned(p_Result_1_fu_244_p4) < unsigned(zext_ln489_fu_254_p1)) else "0";
    mul_I_V_fu_1077_p3 <= (ap_const_lv13_0 & res_I_V_34_fu_1070_p3);
    p_Result_10_fu_465_p4 <= res_I_V_27_fu_457_p3(11 downto 7);
    p_Result_11_fu_483_p4 <= x_l_I_V_26_fu_449_p3(20 downto 14);
    p_Result_13_fu_540_p4 <= res_I_V_28_fu_534_p3(11 downto 6);
    p_Result_14_fu_558_p4 <= x_l_I_V_27_fu_528_p3(19 downto 12);
    p_Result_16_fu_622_p4 <= res_I_V_29_fu_614_p3(11 downto 5);
    p_Result_17_fu_640_p4 <= x_l_I_V_28_fu_606_p3(18 downto 10);
    p_Result_19_fu_697_p4 <= res_I_V_30_fu_691_p3(11 downto 4);
    p_Result_1_fu_244_p4 <= x_l_I_V_23_fu_210_p3(23 downto 20);
    p_Result_20_fu_715_p4 <= x_l_I_V_fu_685_p3(17 downto 8);
    p_Result_22_fu_779_p4 <= res_I_V_fu_771_p3(11 downto 3);
    p_Result_23_fu_797_p4 <= x_l_I_V_29_fu_763_p3(16 downto 6);
    p_Result_25_fu_854_p4 <= res_I_V_31_fu_848_p3(11 downto 2);
    p_Result_26_fu_872_p4 <= x_l_I_V_30_fu_842_p3(15 downto 4);
    p_Result_28_fu_936_p4 <= res_I_V_32_fu_928_p3(11 downto 1);
    p_Result_29_fu_954_p4 <= x_l_I_V_31_fu_920_p3(14 downto 2);
    p_Result_36_fu_198_p5 <= (zext_ln712_fu_172_p1(26 downto 25) & select_ln323_fu_190_p3 & zext_ln712_fu_172_p1(21 downto 0));
    p_Result_37_fu_270_p5 <= (x_l_I_V_23_fu_210_p3(26 downto 24) & sub_ln265_fu_264_p2 & x_l_I_V_23_fu_210_p3(19 downto 0));
    
    p_Result_38_fu_282_p4_proc : process(res_I_V_24_fu_218_p3)
    begin
        p_Result_38_fu_282_p4 <= res_I_V_24_fu_218_p3;
        p_Result_38_fu_282_p4(10) <= ap_const_lv1_1(0);
    end process;

    p_Result_39_fu_352_p5 <= (x_l_I_V_24_reg_1109(26 downto 23) & sub_ln265_1_reg_1127 & x_l_I_V_24_reg_1109(17 downto 0));
    
    p_Result_40_fu_362_p4_proc : process(res_I_V_25_reg_1115)
    begin
        p_Result_40_fu_362_p4 <= res_I_V_25_reg_1115;
        p_Result_40_fu_362_p4(9) <= ap_const_lv1_1(0);
    end process;

    p_Result_41_fu_427_p5 <= (x_l_I_V_25_fu_371_p3(26 downto 22) & sub_ln265_2_fu_421_p2 & x_l_I_V_25_fu_371_p3(15 downto 0));
    
    p_Result_42_fu_439_p4_proc : process(res_I_V_26_fu_377_p3)
    begin
        p_Result_42_fu_439_p4 <= res_I_V_26_fu_377_p3;
        p_Result_42_fu_439_p4(8) <= ap_const_lv1_1(0);
    end process;

    p_Result_43_fu_509_p5 <= (x_l_I_V_26_reg_1132(26 downto 21) & sub_ln265_3_reg_1150 & x_l_I_V_26_reg_1132(13 downto 0));
    
    p_Result_44_fu_519_p4_proc : process(res_I_V_27_reg_1138)
    begin
        p_Result_44_fu_519_p4 <= res_I_V_27_reg_1138;
        p_Result_44_fu_519_p4(7) <= ap_const_lv1_1(0);
    end process;

    p_Result_45_fu_584_p5 <= (x_l_I_V_27_fu_528_p3(26 downto 20) & sub_ln265_4_fu_578_p2 & x_l_I_V_27_fu_528_p3(11 downto 0));
    
    p_Result_46_fu_596_p4_proc : process(res_I_V_28_fu_534_p3)
    begin
        p_Result_46_fu_596_p4 <= res_I_V_28_fu_534_p3;
        p_Result_46_fu_596_p4(6) <= ap_const_lv1_1(0);
    end process;

    p_Result_47_fu_666_p5 <= (x_l_I_V_28_reg_1155(26 downto 19) & sub_ln265_5_reg_1173 & x_l_I_V_28_reg_1155(9 downto 0));
    
    p_Result_48_fu_676_p4_proc : process(res_I_V_29_reg_1161)
    begin
        p_Result_48_fu_676_p4 <= res_I_V_29_reg_1161;
        p_Result_48_fu_676_p4(5) <= ap_const_lv1_1(0);
    end process;

    p_Result_49_fu_741_p5 <= (x_l_I_V_fu_685_p3(26 downto 18) & sub_ln265_6_fu_735_p2 & x_l_I_V_fu_685_p3(7 downto 0));
    p_Result_4_fu_308_p4 <= res_I_V_25_fu_300_p3(11 downto 9);
    
    p_Result_50_fu_753_p4_proc : process(res_I_V_30_fu_691_p3)
    begin
        p_Result_50_fu_753_p4 <= res_I_V_30_fu_691_p3;
        p_Result_50_fu_753_p4(4) <= ap_const_lv1_1(0);
    end process;

    p_Result_51_fu_823_p5 <= (x_l_I_V_29_reg_1178(26 downto 17) & sub_ln265_7_reg_1196 & x_l_I_V_29_reg_1178(5 downto 0));
    
    p_Result_52_fu_833_p4_proc : process(res_I_V_reg_1184)
    begin
        p_Result_52_fu_833_p4 <= res_I_V_reg_1184;
        p_Result_52_fu_833_p4(3) <= ap_const_lv1_1(0);
    end process;

    p_Result_53_fu_898_p5 <= (x_l_I_V_30_fu_842_p3(26 downto 16) & sub_ln265_8_fu_892_p2 & x_l_I_V_30_fu_842_p3(3 downto 0));
    
    p_Result_54_fu_910_p4_proc : process(res_I_V_31_fu_848_p3)
    begin
        p_Result_54_fu_910_p4 <= res_I_V_31_fu_848_p3;
        p_Result_54_fu_910_p4(2) <= ap_const_lv1_1(0);
    end process;

    p_Result_55_fu_998_p5 <= (x_l_I_V_31_reg_1201(26 downto 15) & sub_ln265_9_reg_1212 & x_l_I_V_31_reg_1201(1 downto 0));
    
    p_Result_56_fu_980_p4_proc : process(res_I_V_32_fu_928_p3)
    begin
        p_Result_56_fu_980_p4 <= res_I_V_32_fu_928_p3;
        p_Result_56_fu_980_p4(1) <= ap_const_lv1_1(0);
    end process;

    p_Result_57_fu_1041_p5 <= (x_l_I_V_32_fu_1008_p3(26 downto 14) & sub_ln265_10_fu_1035_p2);
    
    p_Result_58_fu_1053_p4_proc : process(res_I_V_33_reg_1217)
    begin
        p_Result_58_fu_1053_p4 <= res_I_V_33_reg_1217;
        p_Result_58_fu_1053_p4(0) <= ap_const_lv1_1(0);
    end process;

    p_Result_5_fu_326_p4 <= x_l_I_V_24_fu_292_p3(22 downto 18);
    p_Result_8_fu_383_p4 <= res_I_V_26_fu_377_p3(11 downto 8);
    p_Result_9_fu_401_p4 <= x_l_I_V_25_fu_371_p3(21 downto 16);
    p_Result_s_116_fu_1089_p2 <= "1" when (unsigned(x_l_I_V_33_fu_1062_p3) > unsigned(zext_ln717_fu_1085_p1)) else "0";
    p_Result_s_fu_226_p4 <= res_I_V_24_fu_218_p3(11 downto 10);
    res_I_V_22_fu_1095_p2 <= std_logic_vector(unsigned(res_I_V_34_fu_1070_p3) + unsigned(ap_const_lv12_1));
    res_I_V_24_fu_218_p3 <= 
        ap_const_lv12_800 when (tmp_fu_176_p3(0) = '1') else 
        ap_const_lv12_0;
    res_I_V_25_fu_300_p3 <= 
        res_I_V_24_fu_218_p3 when (icmp_ln489_fu_258_p2(0) = '1') else 
        p_Result_38_fu_282_p4;
    res_I_V_26_fu_377_p3 <= 
        res_I_V_25_reg_1115 when (icmp_ln489_1_reg_1121(0) = '1') else 
        p_Result_40_fu_362_p4;
    res_I_V_27_fu_457_p3 <= 
        res_I_V_26_fu_377_p3 when (icmp_ln489_2_fu_415_p2(0) = '1') else 
        p_Result_42_fu_439_p4;
    res_I_V_28_fu_534_p3 <= 
        res_I_V_27_reg_1138 when (icmp_ln489_3_reg_1144(0) = '1') else 
        p_Result_44_fu_519_p4;
    res_I_V_29_fu_614_p3 <= 
        res_I_V_28_fu_534_p3 when (icmp_ln489_4_fu_572_p2(0) = '1') else 
        p_Result_46_fu_596_p4;
    res_I_V_30_fu_691_p3 <= 
        res_I_V_29_reg_1161 when (icmp_ln489_5_reg_1167(0) = '1') else 
        p_Result_48_fu_676_p4;
    res_I_V_31_fu_848_p3 <= 
        res_I_V_reg_1184 when (icmp_ln489_7_reg_1190(0) = '1') else 
        p_Result_52_fu_833_p4;
    res_I_V_32_fu_928_p3 <= 
        res_I_V_31_fu_848_p3 when (icmp_ln489_8_fu_886_p2(0) = '1') else 
        p_Result_54_fu_910_p4;
    res_I_V_33_fu_990_p3 <= 
        res_I_V_32_fu_928_p3 when (icmp_ln489_9_fu_968_p2(0) = '1') else 
        p_Result_56_fu_980_p4;
    res_I_V_34_fu_1070_p3 <= 
        res_I_V_33_reg_1217 when (icmp_ln489_10_fu_1029_p2(0) = '1') else 
        p_Result_58_fu_1053_p4;
    res_I_V_fu_771_p3 <= 
        res_I_V_30_fu_691_p3 when (icmp_ln489_6_fu_729_p2(0) = '1') else 
        p_Result_50_fu_753_p4;
    select_ln323_fu_190_p3 <= 
        ap_const_lv3_7 when (xor_ln265_fu_184_p2(0) = '1') else 
        ap_const_lv3_0;
    sub_ln265_10_fu_1035_p2 <= std_logic_vector(unsigned(trunc_ln640_fu_1021_p1) - unsigned(zext_ln489_10_fu_1025_p1));
    sub_ln265_1_fu_346_p2 <= std_logic_vector(unsigned(p_Result_5_fu_326_p4) - unsigned(zext_ln489_1_fu_336_p1));
    sub_ln265_2_fu_421_p2 <= std_logic_vector(unsigned(p_Result_9_fu_401_p4) - unsigned(zext_ln489_2_fu_411_p1));
    sub_ln265_3_fu_503_p2 <= std_logic_vector(unsigned(p_Result_11_fu_483_p4) - unsigned(zext_ln489_3_fu_493_p1));
    sub_ln265_4_fu_578_p2 <= std_logic_vector(unsigned(p_Result_14_fu_558_p4) - unsigned(zext_ln489_4_fu_568_p1));
    sub_ln265_5_fu_660_p2 <= std_logic_vector(unsigned(p_Result_17_fu_640_p4) - unsigned(zext_ln489_5_fu_650_p1));
    sub_ln265_6_fu_735_p2 <= std_logic_vector(unsigned(p_Result_20_fu_715_p4) - unsigned(zext_ln489_6_fu_725_p1));
    sub_ln265_7_fu_817_p2 <= std_logic_vector(unsigned(p_Result_23_fu_797_p4) - unsigned(zext_ln489_7_fu_807_p1));
    sub_ln265_8_fu_892_p2 <= std_logic_vector(unsigned(p_Result_26_fu_872_p4) - unsigned(zext_ln489_8_fu_882_p1));
    sub_ln265_9_fu_974_p2 <= std_logic_vector(unsigned(p_Result_29_fu_954_p4) - unsigned(zext_ln489_9_fu_964_p1));
    sub_ln265_fu_264_p2 <= std_logic_vector(unsigned(p_Result_1_fu_244_p4) - unsigned(zext_ln489_fu_254_p1));
    tmp_10_fu_1014_p3 <= (res_I_V_33_reg_1217 & ap_const_lv1_1);
    tmp_1_fu_236_p3 <= (p_Result_s_fu_226_p4 & ap_const_lv1_1);
    tmp_2_fu_318_p3 <= (p_Result_4_fu_308_p4 & ap_const_lv1_1);
    tmp_3_fu_393_p3 <= (p_Result_8_fu_383_p4 & ap_const_lv1_1);
    tmp_4_fu_475_p3 <= (p_Result_10_fu_465_p4 & ap_const_lv1_1);
    tmp_5_fu_550_p3 <= (p_Result_13_fu_540_p4 & ap_const_lv1_1);
    tmp_6_fu_632_p3 <= (p_Result_16_fu_622_p4 & ap_const_lv1_1);
    tmp_7_fu_707_p3 <= (p_Result_19_fu_697_p4 & ap_const_lv1_1);
    tmp_8_fu_789_p3 <= (p_Result_22_fu_779_p4 & ap_const_lv1_1);
    tmp_9_fu_864_p3 <= (p_Result_25_fu_854_p4 & ap_const_lv1_1);
    tmp_fu_176_p3 <= x_int_reg(22 downto 22);
    tmp_s_fu_946_p3 <= (p_Result_28_fu_936_p4 & ap_const_lv1_1);
    trunc_ln640_fu_1021_p1 <= x_l_I_V_32_fu_1008_p3(14 - 1 downto 0);
    x_l_I_V_23_fu_210_p3 <= 
        p_Result_36_fu_198_p5 when (tmp_fu_176_p3(0) = '1') else 
        zext_ln712_fu_172_p1;
    x_l_I_V_24_fu_292_p3 <= 
        x_l_I_V_23_fu_210_p3 when (icmp_ln489_fu_258_p2(0) = '1') else 
        p_Result_37_fu_270_p5;
    x_l_I_V_25_fu_371_p3 <= 
        x_l_I_V_24_reg_1109 when (icmp_ln489_1_reg_1121(0) = '1') else 
        p_Result_39_fu_352_p5;
    x_l_I_V_26_fu_449_p3 <= 
        x_l_I_V_25_fu_371_p3 when (icmp_ln489_2_fu_415_p2(0) = '1') else 
        p_Result_41_fu_427_p5;
    x_l_I_V_27_fu_528_p3 <= 
        x_l_I_V_26_reg_1132 when (icmp_ln489_3_reg_1144(0) = '1') else 
        p_Result_43_fu_509_p5;
    x_l_I_V_28_fu_606_p3 <= 
        x_l_I_V_27_fu_528_p3 when (icmp_ln489_4_fu_572_p2(0) = '1') else 
        p_Result_45_fu_584_p5;
    x_l_I_V_29_fu_763_p3 <= 
        x_l_I_V_fu_685_p3 when (icmp_ln489_6_fu_729_p2(0) = '1') else 
        p_Result_49_fu_741_p5;
    x_l_I_V_30_fu_842_p3 <= 
        x_l_I_V_29_reg_1178 when (icmp_ln489_7_reg_1190(0) = '1') else 
        p_Result_51_fu_823_p5;
    x_l_I_V_31_fu_920_p3 <= 
        x_l_I_V_30_fu_842_p3 when (icmp_ln489_8_fu_886_p2(0) = '1') else 
        p_Result_53_fu_898_p5;
    x_l_I_V_32_fu_1008_p3 <= 
        x_l_I_V_31_reg_1201 when (icmp_ln489_9_reg_1207(0) = '1') else 
        p_Result_55_fu_998_p5;
    x_l_I_V_33_fu_1062_p3 <= 
        x_l_I_V_32_fu_1008_p3 when (icmp_ln489_10_fu_1029_p2(0) = '1') else 
        p_Result_57_fu_1041_p5;
    x_l_I_V_fu_685_p3 <= 
        x_l_I_V_28_reg_1155 when (icmp_ln489_5_reg_1167(0) = '1') else 
        p_Result_47_fu_666_p5;
    xor_ln265_fu_184_p2 <= (tmp_fu_176_p3 xor ap_const_lv1_1);
    zext_ln489_10_fu_1025_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_1014_p3),14));
    zext_ln489_1_fu_336_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_318_p3),5));
    zext_ln489_2_fu_411_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_393_p3),6));
    zext_ln489_3_fu_493_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_475_p3),7));
    zext_ln489_4_fu_568_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_550_p3),8));
    zext_ln489_5_fu_650_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_632_p3),9));
    zext_ln489_6_fu_725_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_707_p3),10));
    zext_ln489_7_fu_807_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_789_p3),11));
    zext_ln489_8_fu_882_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_864_p3),12));
    zext_ln489_9_fu_964_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_946_p3),13));
    zext_ln489_fu_254_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_236_p3),4));
    zext_ln712_fu_172_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_int_reg),27));
    zext_ln717_fu_1085_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_I_V_fu_1077_p3),27));
end behav;
